version: '3.9'

services:

  api:
    build: .
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Environment=Production
      - CustomersApi_Database__ConnectionString=Server=projectmanager;Port=5432;Database=projectmanagerDbTests;User ID=postgres;Password=postgrespw;
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=projectmanagerDbTests
    ports:
      - '5432:5432'
